// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ASTeterin/gophkeeper/internal/model (interfaces: PrivateDataRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mock/mock_privacydata.go -package=mock github.com/ASTeterin/gophkeeper/internal/model PrivateDataRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/ASTeterin/gophkeeper/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPrivateDataRepository is a mock of PrivateDataRepository interface.
type MockPrivateDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataRepositoryMockRecorder
	isgomock struct{}
}

// MockPrivateDataRepositoryMockRecorder is the mock recorder for MockPrivateDataRepository.
type MockPrivateDataRepositoryMockRecorder struct {
	mock *MockPrivateDataRepository
}

// NewMockPrivateDataRepository creates a new mock instance.
func NewMockPrivateDataRepository(ctrl *gomock.Controller) *MockPrivateDataRepository {
	mock := &MockPrivateDataRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataRepository) EXPECT() *MockPrivateDataRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPrivateDataRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPrivateDataRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrivateDataRepository)(nil).Delete), ctx, id)
}

// GetByUserAndKey mocks base method.
func (m *MockPrivateDataRepository) GetByUserAndKey(ctx context.Context, userID uuid.UUID, dataKey string) (*model.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndKey", ctx, userID, dataKey)
	ret0, _ := ret[0].(*model.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndKey indicates an expected call of GetByUserAndKey.
func (mr *MockPrivateDataRepositoryMockRecorder) GetByUserAndKey(ctx, userID, dataKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndKey", reflect.TypeOf((*MockPrivateDataRepository)(nil).GetByUserAndKey), ctx, userID, dataKey)
}

// ListByUserID mocks base method.
func (m *MockPrivateDataRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*model.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockPrivateDataRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockPrivateDataRepository)(nil).ListByUserID), ctx, userID)
}

// ReplaceAllData mocks base method.
func (m *MockPrivateDataRepository) ReplaceAllData(ctx context.Context, userID uuid.UUID, items []*model.PrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAllData", ctx, userID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAllData indicates an expected call of ReplaceAllData.
func (mr *MockPrivateDataRepositoryMockRecorder) ReplaceAllData(ctx, userID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAllData", reflect.TypeOf((*MockPrivateDataRepository)(nil).ReplaceAllData), ctx, userID, items)
}

// Store mocks base method.
func (m *MockPrivateDataRepository) Store(ctx context.Context, data *model.PrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockPrivateDataRepositoryMockRecorder) Store(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockPrivateDataRepository)(nil).Store), ctx, data)
}
