// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ASTeterin/gophkeeper/internal/api (interfaces: PrivateDataService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mock/mock_privacydataservice.go -package=mock github.com/ASTeterin/gophkeeper/internal/api PrivateDataService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	contracts "github.com/ASTeterin/gophkeeper/internal/api"
	model "github.com/ASTeterin/gophkeeper/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPrivateDataService is a mock of PrivateDataService interface.
type MockPrivateDataService struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateDataServiceMockRecorder
	isgomock struct{}
}

// MockPrivateDataServiceMockRecorder is the mock recorder for MockPrivateDataService.
type MockPrivateDataServiceMockRecorder struct {
	mock *MockPrivateDataService
}

// NewMockPrivateDataService creates a new mock instance.
func NewMockPrivateDataService(ctrl *gomock.Controller) *MockPrivateDataService {
	mock := &MockPrivateDataService{ctrl: ctrl}
	mock.recorder = &MockPrivateDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateDataService) EXPECT() *MockPrivateDataServiceMockRecorder {
	return m.recorder
}

// AddData mocks base method.
func (m *MockPrivateDataService) AddData(ctx context.Context, userID uuid.UUID, key, desc string, data []byte) (*model.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddData", ctx, userID, key, desc, data)
	ret0, _ := ret[0].(*model.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddData indicates an expected call of AddData.
func (mr *MockPrivateDataServiceMockRecorder) AddData(ctx, userID, key, desc, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddData", reflect.TypeOf((*MockPrivateDataService)(nil).AddData), ctx, userID, key, desc, data)
}

// DeleteData mocks base method.
func (m *MockPrivateDataService) DeleteData(ctx context.Context, userID uuid.UUID, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, userID, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockPrivateDataServiceMockRecorder) DeleteData(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockPrivateDataService)(nil).DeleteData), ctx, userID, key)
}

// GetAllData mocks base method.
func (m *MockPrivateDataService) GetAllData(ctx context.Context, userID uuid.UUID) ([]*model.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", ctx, userID)
	ret0, _ := ret[0].([]*model.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockPrivateDataServiceMockRecorder) GetAllData(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockPrivateDataService)(nil).GetAllData), ctx, userID)
}

// GetDataByKey mocks base method.
func (m *MockPrivateDataService) GetDataByKey(ctx context.Context, userID uuid.UUID, key string) (*model.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByKey", ctx, userID, key)
	ret0, _ := ret[0].(*model.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByKey indicates an expected call of GetDataByKey.
func (mr *MockPrivateDataServiceMockRecorder) GetDataByKey(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByKey", reflect.TypeOf((*MockPrivateDataService)(nil).GetDataByKey), ctx, userID, key)
}

// ReplaceAllData mocks base method.
func (m *MockPrivateDataService) ReplaceAllData(ctx context.Context, userID uuid.UUID, items []contracts.DataItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAllData", ctx, userID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAllData indicates an expected call of ReplaceAllData.
func (mr *MockPrivateDataServiceMockRecorder) ReplaceAllData(ctx, userID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAllData", reflect.TypeOf((*MockPrivateDataService)(nil).ReplaceAllData), ctx, userID, items)
}
